### ISSUE TITLE
4th feature

### ISSUE THREAD

**Issue by jackson910210** [Chloe-Ku/WolfJobs#5]
Save Jobs、Jobs status(waiting to be reviewed, under review, rejected, accepted to be interviewed)

**Comment by Chloe-Ku** [comment]
Hi all,
I have finished the function of saving job and present the saved job list.
Welcome to share any question and comment with me, thanks

**Comment by Chloe-Ku** [comment]
Hi all,
I have finished the function of showing job status.
Welcome to share any question and comment with me, thanks
